remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Optimizing WiFi Sensing for Human Activity Recognition with Reduced Sampling Rates
description: Project for UCLA ECEM202A/CSM213A (Fall 2023)
